theme: "ananke"
baseURL: "https://ftisiot.net"
languageCode : "en-us"
title: "ftisiot ideas about tech, food and life"
googleAnalytics: "G-7Z74BTZ0TM"
paginate: 10
pygmentsStyle: pygments



params:
  ananke_socials:
  - name: twitter
    url: https://twitter.com/FTisiot
  - name: github
    url: https://github.com/ftisiot
  - name: linkedin
    url: https://www.linkedin.com/in/francescotisiot/
  - name: youtube
    url: https://www.youtube.com/channel/UCTJ4oA3-T3RdmM2OJ7d8cJg
  - name: mastodon
    url: https://data-folks.masto.host/@ftisiot
  AuthorName: Francesco Tisiot
  GitHubUser: "ftisiot"
  image: "images/ftisiot.jpg"
  enableEmoji: true
  GoogleAnalyticsID: "G-7Z74BTZ0TM"

permalinks:
  post: /:year/:month/:day/:title/

taxonomies:
  category: categories
  tag: tag

outputs:
   home:
      - HTML
      - JSON
      - RSS
   page:
      - HTML
   section:
      - HTML
      - RSS
   taxonomy:
      - HTML
      - RSS

menu:
  main:
  - name: about
    title: who
    url: /who
    weight: -10
  - name: suggestions
    title: suggestions
    url: /suggestions-verona
    weight: -8
  - name: json-pg
    title: json-pg
    url: /postgresqljson/main
    weight: -6
  - name: json-mysql
    title: json-mysql
    url: /mysqljson/main
    weight: -5

markup:
  asciidocExt:
    attributes: {allow-uri-read}
    safeMode: unsafe
    enableEmoji: true
  goldmark:
    renderer:
      unsafe: true
