theme: "mystory"
baseURL: "https://ftisiot.net"
languageCode : "en-us"
title: "ftisiot ideas about food and life"
googleAnalytics: "G-7Z74BTZ0TM"
paginate: 10
pygmentsStyle: pygments


params:
  AuthorName: Francesco Tisiot
  GitHubUser: "ftisiot"
  image: "images/ftisiot.png"
  enableEmoji: true
  GoogleAnalyticsID: "G-7Z74BTZ0TM"

permalinks:
  post: /:year/:month/:day/:title/

taxonomies:
  category: categories
  tag: tag

outputs:
   home:
      - HTML
      - JSON
      - RSS
   page:
      - HTML
   section:
      - HTML
      - RSS
   taxonomy:
      - HTML
      - RSS
   taxonomyTerm:
      - HTML
      - RSS

menu:
  main:
  - name: who
    title: who
    url: /who
    weight: -10
  - name: talks
    title: talks
    url: /speaking-activities
    weight: -9
  - name: suggestions
    title: suggestions
    url: /suggestions-verona
    weight: -8
  - name: json-pg
    title: json-pg
    url: /postgresqljson/main
    weight: -7
  social:
  - name: github
    title: "fab fa-github-square"
    url: https://github.com/ftisiot/
    weight: -6
  - name: youtube
    title: "fab fa-youtube-square"
    url: https://www.youtube.com/channel/UCTJ4oA3-T3RdmM2OJ7d8cJg
    weight: -8
  - name: twitter
    title: "fab fa-twitter-square"
    url: https://twitter.com/ftisiot/
    weight: -7
  - name: linkedin
    title: "fab fa-linkedin"
    url: https://www.linkedin.com/in/francescotisiot/
    weight: -5

markup:
  asciidocExt:
    attributes: {allow-uri-read}
    safeMode: unsafe
    enableEmoji: true
  goldmark:
    renderer:
      unsafe: true
